### ISSUE TITLE
Broken map layout switching

### ISSUE THREAD

**Issue by zdila** [PaulLeCam/react-leaflet#300]
After upgrading from 1.1.1 to 1.1.2 the map layer switchng stopped working - mouse over on the buddon make it change its size to 10x10px of so and clicking it the does nothing.

Also `TileLayer` immediately fires `add` event for every `LayersControl.BaseLayer` and `LayersControl.Overlay` it includes.

**Comment by seanes** [comment]
I ran into the same issue when bumping version of `babel-cli`and `babel-core`and am curious as to the cause is related to. [v. 1.1.2, cf.](https://github.com/PaulLeCam/react-leaflet/commit/83a10ae653676d72fe3e94eec3e89a1fa694cf26)

Seems like some functions are missing. Ultimately rendering `removeLayerControl is not a function`

**Comment by jampy** [comment]
Apparently all base layers are displayed at the same time in 1.1.2

**Comment by PaulLeCam** [comment]
Please try upgrading to v1.1.3, it should fix the issue.

**Comment by zdila** [comment]
Thanks. With 1.1.3 it works correctly.
