### ISSUE TITLE
Implement riseOnHover Marker option

### ISSUE THREAD

**Issue by brienna** [PaulLeCam/react-leaflet#907]
[Leaflet reference](https://leafletjs.com/reference-1.7.1.html): 

> `riseOnHover`: If true, the marker will get on top of others when you hover the mouse over it.

[React-leaflet reference](https://react-leaflet.js.org/docs/api-components/#marker) has a subset of the Leaflet Marker options implemented. It does not implement the `riseOnHover` option. 

Is it possible to either implement this option, or to describe in the documentation how one would get this original Leaflet functionality?

**Comment by ccallendar** [comment]
Hi Brienna, it looks like `riseOnHover` should work as react-leaflet just passes all the props along as options to the Leaflet Marker.

For me this works in react-leaflet 3.2.1:
```
<Marker position={latlng} riseOnHover />
```

You can also control the zIndex manually by setting the `zIndexOffset`. In my use case I wanted the selected marker to be on top of the others, so I have something like this:
```
<Marker position={latlng} riseOnHover zIndexOffset={isSelected ? 2 : 1} />
```

Hope that helps.

**Comment by brienna** [comment]
Thank you, this helps!

**Comment by AyeshaAzam** [comment]
Hi, Using same leaflet map as @[brienna](https://github.com/brienna) but the vue2 leaflet version.
For me when I add 'riseOnHover' property then its doesnot work and also  zIndexOffset.
I am struggling with this for few days now and still no luck so far, Any help or advice will be much appreciated.

```
<l-tile-layer
          url="https://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png"
          attribution='&copy; <a target="_blank" href="http://osm.org/copyright">OpenStreetMap</a>'
        ></l-tile-layer>
        <l-marker
          v-for="(place, index) in places"
          :key="index"
          :lat-lng="[place.location.latitude, place.location.longitude]"
          :z-index-offset="selectedMarkerIndex === index ? 51 : undefined"  // for some reason the Eslint hyphenated, but same 
                             issue if I try with zIndexOffset
          riseOnHover="riseOnHover = true"
          @click="[place.location.latitude, place.location.longitude], (activeMarkerIndex = index)"
          @keydown.enter="openPopupOnEnterPress(index)"
          @focus="showPopup = !showPopup"
        >
          <l-icon :icon-anchor="iconAnchor" :icon-size="iconSize" :popup-anchor="popupAnchor">
            <DlMapMarker :text="place.name" />
          </l-icon>

          <l-popup @keydown.enter="openPopupOnEnterPress(index)" @focus="showPopup = !showPopup">
            <h2>Name: {{ place.name }}</h2>
              <br />
               <h3>Address: {{ place.address }} </h3> 
          </l-popup>
        </l-marker>

```
